# -*- coding: utf-8 -*-
"""26.05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vEKPaaQ47d9nirWnK1CsA2r9uqShsd4N
"""

print "Привет мир"